import Head from "next/head";
import { Inter } from "next/font/google";
import { Flex, Select, Text } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Flex
          flexDir="column"
          alignItems="center"
          justifyContent="center"
          minH="100vh"
          maxW="5xl"
          mx="auto"
          p={4}
        >
          <Text fontSize="2xl" textTransform="uppercase" letterSpacing="10px">
            Hello World
          </Text>
          <Select maxW="100px" mt={2}>
            <option value="id">ID</option>
            <option value="en">EN</option>
          </Select>
        </Flex>
      </main>
    </>
  );
}
